// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: HelloBalls_ui

#include "../ui.h"

void ui_ScreenMainMenu_screen_init(void)
{
    ui_ScreenMainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMainMenu, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuTextareaTextArea2 = lv_textarea_create(ui_ScreenMainMenu);
    lv_obj_set_width(ui_MainMenuTextareaTextArea2, 144);
    lv_obj_set_height(ui_MainMenuTextareaTextArea2, 211);
    lv_obj_set_x(ui_MainMenuTextareaTextArea2, 73);
    lv_obj_set_y(ui_MainMenuTextareaTextArea2, -1);
    lv_obj_set_align(ui_MainMenuTextareaTextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MainMenuTextareaTextArea2, "Initing...");
    lv_textarea_set_placeholder_text(ui_MainMenuTextareaTextArea2, "No motor detected");
    lv_obj_clear_flag(ui_MainMenuTextareaTextArea2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MainMenuTextareaTextArea2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_text_color(ui_MainMenuTextareaTextArea2, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuTextareaTextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenuTextareaTextArea2, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuTextareaTextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_MainMenuTextareaTextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuContainerContainer1 = lv_obj_create(ui_ScreenMainMenu);
    lv_obj_remove_style_all(ui_MainMenuContainerContainer1);
    lv_obj_set_width(ui_MainMenuContainerContainer1, 83);
    lv_obj_set_height(ui_MainMenuContainerContainer1, 51);
    lv_obj_set_align(ui_MainMenuContainerContainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainMenuContainerContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainMenuLabelLabel1 = lv_label_create(ui_MainMenuContainerContainer1);
    lv_obj_set_width(ui_MainMenuLabelLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLabelLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenuLabelLabel1, 0);
    lv_obj_set_y(ui_MainMenuLabelLabel1, 15);
    lv_obj_set_align(ui_MainMenuLabelLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenuLabelLabel1, "Receive");
    lv_obj_set_style_text_color(ui_MainMenuLabelLabel1, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLabelLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuSwitchSwitch1 = lv_switch_create(ui_MainMenuContainerContainer1);
    lv_obj_set_width(ui_MainMenuSwitchSwitch1, 64);
    lv_obj_set_height(ui_MainMenuSwitchSwitch1, 25);
    lv_obj_set_x(ui_MainMenuSwitchSwitch1, 0);
    lv_obj_set_y(ui_MainMenuSwitchSwitch1, -10);
    lv_obj_set_align(ui_MainMenuSwitchSwitch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MainMenuSwitchSwitch1, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuSwitchSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuContainerContainer2 = lv_obj_create(ui_ScreenMainMenu);
    lv_obj_remove_style_all(ui_MainMenuContainerContainer2);
    lv_obj_set_width(ui_MainMenuContainerContainer2, 128);
    lv_obj_set_height(ui_MainMenuContainerContainer2, 133);
    lv_obj_set_x(ui_MainMenuContainerContainer2, 17);
    lv_obj_set_y(ui_MainMenuContainerContainer2, -26);
    lv_obj_set_align(ui_MainMenuContainerContainer2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_MainMenuContainerContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MainMenuContainerContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuSliderSlider1 = lv_slider_create(ui_MainMenuContainerContainer2);
    lv_slider_set_range(ui_MainMenuSliderSlider1, -1000, 1000);
    lv_slider_set_value(ui_MainMenuSliderSlider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MainMenuSliderSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_MainMenuSliderSlider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainMenuSliderSlider1, 112);
    lv_obj_set_height(ui_MainMenuSliderSlider1, 8);
    lv_obj_set_x(ui_MainMenuSliderSlider1, 0);
    lv_obj_set_y(ui_MainMenuSliderSlider1, 4);
    lv_obj_set_align(ui_MainMenuSliderSlider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MainMenuSliderSlider1, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuSliderSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainMenuSliderSlider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuSliderSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainMenuSliderSlider1, lv_color_hex(0xC5C5C5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuSliderSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MainMenuButtonTestButton = lv_btn_create(ui_MainMenuContainerContainer2);
    lv_obj_set_width(ui_MainMenuButtonTestButton, 114);
    lv_obj_set_height(ui_MainMenuButtonTestButton, 31);
    lv_obj_set_x(ui_MainMenuButtonTestButton, 0);
    lv_obj_set_y(ui_MainMenuButtonTestButton, -10);
    lv_obj_set_align(ui_MainMenuButtonTestButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MainMenuButtonTestButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainMenuButtonTestButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainMenuButtonTestButton, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenuButtonTestButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuLabelTestButtonLabel = lv_label_create(ui_MainMenuButtonTestButton);
    lv_obj_set_width(ui_MainMenuLabelTestButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLabelTestButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenuLabelTestButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenuLabelTestButtonLabel, "RUN MOTOR");
    lv_obj_set_style_text_color(ui_MainMenuLabelTestButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLabelTestButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuLabelLabel4 = lv_label_create(ui_MainMenuContainerContainer2);
    lv_obj_set_width(ui_MainMenuLabelLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLabelLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMenuLabelLabel4, -1);
    lv_obj_set_y(ui_MainMenuLabelLabel4, -20);
    lv_obj_set_align(ui_MainMenuLabelLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenuLabelLabel4, "SPEED");
    lv_obj_set_style_text_color(ui_MainMenuLabelLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLabelLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainMenuSwitchSwitch1, ui_event_MainMenuSwitchSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenuSliderSlider1, ui_event_MainMenuSliderSlider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenuButtonTestButton, ui_event_MainMenuButtonTestButton, LV_EVENT_ALL, NULL);
    uic_ScreenMainMenu = ui_ScreenMainMenu;
    uic_TextArea2 = ui_MainMenuTextareaTextArea2;
    uic_MainMenuLabelTestButtonLabel = ui_MainMenuLabelTestButtonLabel;

}
