// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenScreen1_screen_init(void)
{
    ui_ScreenScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ButtonTestButton = lv_btn_create(ui_ScreenScreen1);
    lv_obj_set_width(ui_Screen1ButtonTestButton, 101);
    lv_obj_set_height(ui_Screen1ButtonTestButton, 31);
    lv_obj_set_x(ui_Screen1ButtonTestButton, -88);
    lv_obj_set_y(ui_Screen1ButtonTestButton, -45);
    lv_obj_set_align(ui_Screen1ButtonTestButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonTestButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1ButtonTestButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1ButtonTestButton, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1ButtonTestButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1LabelTestButtonLabel = lv_label_create(ui_Screen1ButtonTestButton);
    lv_obj_set_width(ui_Screen1LabelTestButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1LabelTestButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1LabelTestButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1LabelTestButtonLabel, "RUN MOTOR");
    lv_obj_set_style_text_color(ui_Screen1LabelTestButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1LabelTestButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1SwitchSwitch1 = lv_switch_create(ui_ScreenScreen1);
    lv_obj_set_width(ui_Screen1SwitchSwitch1, 50);
    lv_obj_set_height(ui_Screen1SwitchSwitch1, 25);
    lv_obj_set_x(ui_Screen1SwitchSwitch1, -88);
    lv_obj_set_y(ui_Screen1SwitchSwitch1, 42);
    lv_obj_set_align(ui_Screen1SwitchSwitch1, LV_ALIGN_CENTER);

    ui_Screen1LabelLabel1 = lv_label_create(ui_ScreenScreen1);
    lv_obj_set_width(ui_Screen1LabelLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1LabelLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1LabelLabel1, -87);
    lv_obj_set_y(ui_Screen1LabelLabel1, 68);
    lv_obj_set_align(ui_Screen1LabelLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1LabelLabel1, "Receive");

    ui_Screen1TextareaTextArea2 = lv_textarea_create(ui_ScreenScreen1);
    lv_obj_set_width(ui_Screen1TextareaTextArea2, 144);
    lv_obj_set_height(ui_Screen1TextareaTextArea2, 202);
    lv_obj_set_x(ui_Screen1TextareaTextArea2, 60);
    lv_obj_set_y(ui_Screen1TextareaTextArea2, -1);
    lv_obj_set_align(ui_Screen1TextareaTextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Screen1TextareaTextArea2, "Initing...");
    lv_textarea_set_placeholder_text(ui_Screen1TextareaTextArea2, "No motor detected");
    lv_obj_clear_flag(ui_Screen1TextareaTextArea2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1TextareaTextArea2, LV_SCROLLBAR_MODE_ACTIVE);

    lv_obj_add_event_cb(ui_Screen1ButtonTestButton, ui_event_Screen1ButtonTestButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1SwitchSwitch1, ui_event_Screen1SwitchSwitch1, LV_EVENT_ALL, NULL);
    uic_Screen1LabelTestButtonLabel = ui_Screen1LabelTestButtonLabel;
    uic_TextArea2 = ui_Screen1TextareaTextArea2;

}
