// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenScreen1
void ui_ScreenScreen1_screen_init(void);
lv_obj_t * ui_ScreenScreen1;
void ui_event_Screen1ButtonTestButton(lv_event_t * e);
lv_obj_t * ui_Screen1ButtonTestButton;
lv_obj_t * ui_Screen1LabelTestButtonLabel;
void ui_event_Screen1SwitchSwitch1(lv_event_t * e);
lv_obj_t * ui_Screen1SwitchSwitch1;
lv_obj_t * ui_Screen1LabelLabel1;
lv_obj_t * ui_Screen1TextareaTextArea2;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen1LabelTestButtonLabel;
lv_obj_t * uic_TextArea2;

// EVENTS
lv_obj_t * ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1ButtonTestButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lvgl_can_task(e);
    }
}

void ui_event_Screen1SwitchSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvgl_start_twai_receive(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvgl_stop_twai_receive(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenScreen1_screen_init();
    ui_Startevents___initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenScreen1);
}
