// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ScreenScreen1
void ui_ScreenScreen1_screen_init(void);
extern lv_obj_t * ui_ScreenScreen1;
void ui_event_Screen1ButtonTestButton(lv_event_t * e);
extern lv_obj_t * ui_Screen1ButtonTestButton;
extern lv_obj_t * ui_Screen1LabelTestButtonLabel;
void ui_event_Screen1SwitchSwitch1(lv_event_t * e);
extern lv_obj_t * ui_Screen1SwitchSwitch1;
extern lv_obj_t * ui_Screen1LabelLabel1;
extern lv_obj_t * ui_Screen1TextareaTextArea2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1LabelTestButtonLabel;
extern lv_obj_t * uic_TextArea2;

// EVENTS

extern lv_obj_t * ui_Startevents___initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
