// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: HelloBalls_ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "custom_header.h"

void lvgl_start_twai_receive(lv_event_t * e);
void lvgl_stop_twai_receive(lv_event_t * e);
void lvgl_set_global_speed(lv_event_t * e);
void lvgl_can_task(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
