// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "app_twai.h"

void lvgl_can_task(lv_event_t * e)
{
	can_task();
}
